-- ========================================================
-- COMPREHENSIVE EGYPTIAN UNIVERSITIES DATASET MIGRATION
-- ========================================================

INSERT INTO public.universities (name, short_name, location) VALUES
('Cairo University', 'CU', 'Giza'),
('Ain Shams University', 'ASU', 'Cairo'),
('Alexandria University', 'ALEXU', 'Alexandria'),
('Mansoura University', 'MANSU', 'Mansoura'),
('Zagazig University', 'ZU', 'Zagazig'),
('Assiut University', 'AUN', 'Assiut'),
('Tanta University', 'TU', 'Tanta'),
('Helwan University', 'HU', 'Cairo'),
('Minia University', 'MU', 'Minia'),
('Menoufia University', 'MNFU', 'Shebin El-Kom'),
('Suez Canal University', 'SCU', 'Ismailia'),
('South Valley University', 'SVU', 'Qena'),
('Benha University', 'BU', 'Benha'),
('Fayoum University', 'FU', 'Fayoum'),
('Beni Suef University', 'BSU', 'Beni Suef'),
('Kafrelsheikh University', 'KFS', 'Kafr El Sheikh'),
('Sohag University', 'SOHAG', 'Sohag'),
('Port Said University', 'PSU', 'Port Said'),
('Damanhour University', 'DAMU', 'Damanhour'),
('Aswan University', 'ASWU', 'Aswan'),
('Damietta University', 'DU', 'Damietta'),
('Sadat City University (University of Sadat City)', 'USC', 'Sadat City'),
('Suez University', 'SU', 'Suez'),
('Arish University', 'AU', 'Arish'),
('New Valley University', 'NVU', 'Kharga'),
('Matrouh University', 'MATROUH', 'Marsa Matrouh'),
('Luxor University', 'LUXOR', 'Luxor'),
('Hurghada University', 'HURGHADA', 'Hurghada'),
('Al-Azhar University', 'AZHAR', 'Cairo'),
('Military Technical College', 'MTC', 'Cairo'),
('Sadat Academy for Management Sciences', 'SAMS', 'Cairo'),
('Egypt-Japan University of Science and Technology (E-JUST)', 'E-JUST', 'New Borg El Arab, Alexandria'),
('Zewail City of Science and Technology', 'ZCST', '6th of October City'),
('New Mansoura University', 'NMU', 'New Mansoura'),
('Galala University', 'GU', 'Ain Sokhna, Suez Governorate'),
('Alamein International University', 'AIU', 'El Alamein'),
('King Salman International University', 'KSIU', 'South Sinai'),
('Egypt University of Informatics (EUI)', 'EUI', 'New Administrative Capital'),
('French University in Egypt (UFE)', 'UFE', 'New Administrative Capital'),
('Nile University', 'NU', 'Sheikh Zayed City, Giza'),
('Egyptian E-Learning University (EELU)', 'EELU', 'Cairo (online)'),
('Ain Shams National University', 'ASNU', 'Cairo'),
('Assiut National University', 'AUNU', 'Assiut'),
('Benha National University', 'BNU', 'Benha'),
('Cairo National University', 'CNU', 'Cairo'),
('Damanhour National University', 'DNU', 'Damanhour'),
('Damietta National University', 'DMNU', 'Damietta'),
('East Port Said National University', 'EPSNU', 'Port Said'),
('Fayoum National University', 'FNU', 'Fayoum'),
('Helwan National University', 'HNU', 'Cairo'),
('Kafr El Sheikh National University', 'KFSNU', 'Kafr El Sheikh'),
('Luxor National University', 'LNU', 'Luxor'),
('Mansoura National University', 'MNU', 'Mansoura'),
('Menoufia National University', 'MNFNU', 'Shebin El-Kom'),
('Minia National University', 'MINU', 'Minia'),
('New Valley National University', 'NVNU', 'Kharga'),
('New Ismailia National University', 'NINU', 'Ismailia'),
('Sohag National University', 'SGNU', 'Sohag'),
('South Valley National University', 'SVNU', 'Qena'),
('Tanta National University', 'TNU', 'Tanta'),
('Zagazig National University', 'ZNU', 'Zagazig'),
('American University in Cairo (AUC)', 'AUC', 'New Cairo'),
('German University in Cairo (GUC)', 'GUC', 'New Cairo'),
('German International University (GIU)', 'GIU', 'New Administrative Capital'),
('British University in Egypt (BUE)', 'BUE', 'El Sherouk City / Cairo'),
('University of Hertfordshire in Egypt', 'UH', 'New Administrative Capital'),
('European Universities in Egypt (EUE)', 'EUE', 'New Administrative Capital'),
('Canadian Universities in Egypt (UPEI campus)', 'UPEI', 'New Administrative Capital'),
('TMU Cairo (University of Canada branch)', 'TMU', 'New Administrative Capital'),
('Misr International University (MIU)', 'MIU', 'Cairo'),
('Misr University for Science and Technology (MUST)', 'MUST', '6th of October City'),
('Modern Sciences and Arts University (MSA)', 'MSA', '6th of October City'),
('Modern University for Technology and Information (MTI)', 'MTI', 'Cairo'),
('Ahram Canadian University (ACU)', 'ACU', '6th of October City'),
('Future University in Egypt (FUE)', 'FUE', 'New Cairo'),
('Pharos University in Alexandria (PUA)', 'PUA', 'Alexandria'),
('Newgiza University (NGU)', 'NGU', 'Giza'),
('Arab Academy for Science, Technology and Maritime Transport (AASTMT)', 'AASTMT', 'Alexandria'),
('Arab Open University - Egypt', 'AOU', 'Cairo'),
('Heliopolis University for Sustainable Development', 'HU', 'Cairo'),
('October 6 University', 'O6U', '6th of October City'),
('Egyptian Chinese University', 'ECU', 'Cairo'),
('Egyptian Russian University', 'ERU', 'Badr City'),
('Delta University for Science and Technology', 'DELTA', 'Gamasa, Mansoura'),
('Horus University in Egypt', 'HUE', 'New Damietta'),
('Nahda University (NUB)', 'NUB', 'Beni Suef'),
('Badr University in Cairo (BUC)', 'BUC', 'Badr City'),
('Badr University in Assiut (BUA)', 'BUA', 'Assiut'),
('Badya University', 'BADYA', '6th of October City'),
('Sinai University', 'SU', 'Arish / Kantara'),
('Al Ryada University for Science and Technology (RST)', 'RST', 'Sadat City'),
('Sphinx University', 'SPHINX', 'Assiut'),
('Alsalam University in Egypt (SUE)', 'SUE', 'Kafr El Sheikh / Delta region'),
('ALHAYAH University Cairo (AHUC)', 'AHUC', 'New Administrative Capital'),
('Deraya University in Minya', 'DERAYA', 'Minya'),
('ESLSCA University', 'ESLSCA', 'New Administrative Capital'),
('El Shorouk Academy', 'SHA', 'El Shorouk City'),
('El Sewedy University of Technology (SUT)', 'SUT', '10th of Ramadan City'),
('Canadian International College (CIC)', 'CIC', 'Cairo / 5th Settlement / Zayed'),
('Al Madina University in Cairo (CUC)', 'CUC', 'Cairo'),
('Innovation University', 'IU', 'New Administrative Capital'),
('Lotus University in Minya (LUM)', 'LUM', 'Minya'),
('May University in Cairo (MUC)', 'MUC', 'Cairo'),
('Memphis University', 'MEMPHIS', 'Cairo'),
('Merit University', 'MERIT', 'Sohag / Upper Egypt'),
('Nile Valley University', 'NVU', 'Beni Suef'),
('AL-Rasheed Private University', 'RPU', 'Egypt'),
('Saxony Egypt University (SEU)', 'SEU', '6th of October City')
ON CONFLICT (name) DO NOTHING;
